// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function string_of_readyState(readyState) {
  switch (readyState) {
    case /* CONNECTING */0 :
        return "CONNECTING";
    case /* OPEN */1 :
        return "OPEN";
    case /* CLOSING */2 :
        return "CLOSING";
    case /* CLOSED */3 :
        return "CLOSED";
    
  }
}

exports.string_of_readyState = string_of_readyState;
/* No side effect */
