// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function string_of_readyState(readyState) {
  switch (readyState) {
    case 0 : 
        return "CONNECTING";
    case 1 : 
        return "OPEN";
    case 2 : 
        return "CLOSING";
    case 3 : 
        return "CLOSED";
    
  }
}

exports.string_of_readyState = string_of_readyState;
/* No side effect */
