// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var IsomorphicWs = require("isomorphic-ws");

var ws = new IsomorphicWs("wss://www.example.com");

ws.send("Hello World!");

exports.ws = ws;
/* ws Not a pure module */
