// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Ws = require("ws");

var ws = new Ws("wss://www.example.com");

ws.send("Hello World!");

exports.ws = ws;
/* ws Not a pure module */
