// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Ws = require("ws");

var ws = new Ws("wss://www.example.com");

ws.on("message", (function (data) {
              console.log("Message: " + data);
              return /* () */0;
            })).on("close", (function (code, reason) {
            console.log("Closed: " + (String(code) + reason));
            return /* () */0;
          })).on("open", (function () {
          console.log("Opened!");
          return /* () */0;
        })).on("error", (function (error) {
        console.log("Error: " + error.message);
        return /* () */0;
      }));

exports.ws = ws;
/* ws Not a pure module */
